%% Copyright (c) 2026 Cedric Cannard. GPL-3.0 (see the repository LICENSE).

function opt = galea_process_defaults()
%GALEA_PROCESS_DEFAULTS  Default processing options for the Galea plugin.
%
%   >> opt = galea_process_defaults()
%
% One struct for every processing parameter (EEG and the other signals
% alike), so the main window, the parameters dialog and pop_galea_preprocess
% all speak the same option names.
%
% Cedric Cannard, 2026

opt = struct( ...
    'montage',      'default', ...   % 'default' (10 EEG) or 'custom' (12 EEG, Fp1/Fp2)
    'eeg',          true, ...
    'trim',         3, ...           % s; 0 = keep everything
    'resample',     0, ...           % Hz; 0 = keep
    'locut',        0.5, ...
    'hicut',        30, ...
    'causal',       false, ...
    'polarity',     false, ...       % Fp1/Fp2 lead check (custom montage only)
    'badchan',      true, ...
    'interpchan',   false, ...
    'mincorr',      0.55, ...        % channel cross-correlation threshold (lax .35, aggressive .85)
    'maxtol',       0.30, ...        % max fraction of windows a channel may fail (5-50%)
    'asr',          100, ...         % ASR 1st pass threshold; 0 = skip
    'asrmode',      'remove', ...
    'ica',          true, ...
    'icaconfirm',   true, ...        % command-line only now: the GUI always confirms
    'viseeg',       true, ...
    'eog',          true, ...        % filter EOG + blink detection
    'eoglocut',     0.5, ...
    'eoghicut',     20, ...
    'viseog',       true, ...
    'ppg',          false, 'ppglocut',0.5, 'ppghicut',3, ...
    'ppgdetect',    'valleys', ...   % pulse-wave detection: 'valleys' (default) or 'peaks'
    'rrcorrect',    'pchip', ...     % kept for BrainBeats compatibility; not exposed in the GUI
    'hrvtime',      true, 'hrvfreq',true, 'hrvnonlin',false, 'visppg',true, ...
    'eda',          false, 'edalocut',0.01, 'edahicut',1, ...
    'edaphasic',    false, ...      % cvxEDA tonic/phasic (data auto-downsampled to 8 Hz)
    'viscvx',       true, ...        % plot the tonic/phasic decomposition
    'viseda',       true, ...
    'emg',          false, 'emglocut',20, 'emghicut',0, ...   % 0 = no low-pass
    'emgenvelope',  true, 'visemg',true, ...
    'imu',          false, 'imuhicut',10, 'imumagnitude',true, 'visimu',true);
end