%% Copyright (c) 2026 Cedric Cannard. GPL-3.0 (see the repository LICENSE).

function opt = galea_process_defaults()
%GALEA_PROCESS_DEFAULTS  Default processing options for the Galea plugin.
%
%   >> opt = galea_process_defaults()
%
% One struct for every processing parameter (EEG and the other signals
% alike), so the main window, the parameters dialog and pop_galea_preprocess
% all speak the same option names.
%
% Cedric Cannard, 2026

opt = struct( ...
    'montage',      'default', ...   % 'default' (10 EEG) or 'custom' (12 EEG, Fp1/Fp2)
    'eeg',          true, ...
    'trim',         3, ...           % s; 0 = keep everything
    'resample',     0, ...           % Hz; 0 = keep
    'locut',        0.5, ...
    'hicut',        30, ...
    'causal',       false, ...
    'polarity',     false, ...
    'badchan',      true, ...
    'interpchan',   false, ...
    'mincorr',      0.55, ...        % channel cross-correlation (R^2) threshold
    'maxtol',       0.30, ...        % max fraction of windows a channel may fail
    'asr',          100, ...
    'asrmode',      'remove', ...
    'ica',          true, ...
    'icaconfirm',   true, ...
    'viseeg',       true, ...
    'ppg',          false, 'ppglocut',0.5, 'ppghicut',3, 'rrcorrect','pchip', ...
    'hrvtime',      true, 'hrvfreq',true, 'hrvnonlin',false, 'visppg',true, ...
    'eda',          false, 'edalocut',0.01, 'edahicut',1, 'edaresample',8, ...
    'edaphasic',    false, 'viseda',true, ...
    'emg',          false, 'emglocut',20, 'emgenvelope',true, 'visemg',true, ...
    'imu',          false, 'imuhicut',10, 'imumagnitude',true, 'visimu',true);
end